name: ptmk-app-local-dev

services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env  # path to .env file relative to the current file directory
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
